#ifndef SPOOFUNAME_COMMON_H
#define SPOOFUNAME_COMMON_H

#define SPOOFUNAME_MAGIC_NUMBER1 0x53504F46
#define SPOOFUNAME_MAGIC_NUMBER2 857865690

#define SPOOFUNAME_CMD_GET_STATUS 0
#define SPOOFUNAME_CMD_ENABLE 1
#define SPOOFUNAME_CMD_DISABLE 2
#define SPOOFUNAME_CMD_SET_RELEASE 3
#define SPOOFUNAME_CMD_SET_VERSION 4

#define SPOOFUNAME_MAX_LENGTH 64

#endif